# Generated by Django 5.1.7 on 2025-05-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Accessibilité',
                'verbose_name_plural': 'Accessibilités',
                'db_table': 'accessibilites',
            },
        ),
        migrations.CreateModel(
            name='Type_papier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Type de papiers',
                'verbose_name_plural': 'Type de papiers',
                'db_table': 'types_papiers',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('logement', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Type de logement',
                'verbose_name_plural': 'Types de logement',
                'db_table': 'types',
                'constraints': [models.UniqueConstraint(fields=('nom', 'logement'), name='unique_type_logement')],
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=20)),
                ('commodite', models.CharField(max_length=20)),
                ('nb_chambres', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('accessibilite', models.ForeignKey(db_column='accessibilite', on_delete=django.db.models.deletion.PROTECT, to='estimation.accessibilite')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='estimation.type')),
            ],
            options={
                'verbose_name': 'Maison',
                'verbose_name_plural': 'Maisons',
                'db_table': 'maisons',
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=20)),
                ('superficie', models.IntegerField(help_text='Superficie en m²')),
                ('est_cloture', models.BooleanField(default=False, verbose_name='Clôturé')),
                ('est_pret_a_construire', models.BooleanField(default=False, verbose_name='Prêt à construire')),
                ('prix', models.IntegerField()),
                ('accessibilite', models.ForeignKey(db_column='accessibilite', on_delete=django.db.models.deletion.PROTECT, to='estimation.accessibilite')),
                ('type_papier', models.ForeignKey(db_column='type_papier', on_delete=django.db.models.deletion.PROTECT, to='estimation.type_papier')),
            ],
            options={
                'verbose_name': 'Terrain',
                'verbose_name_plural': 'Terrains',
                'db_table': 'terrains',
            },
        ),
    ]
