# Generated by Django 5.1.7 on 2025-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Commodité',
                'verbose_name_plural': 'Commodités',
                'db_table': 'commodites',
            },
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='superficie',
        ),
        migrations.RemoveField(
            model_name='maison',
            name='commodite',
        ),
        migrations.AddField(
            model_name='maison',
            name='commodite',
            field=models.ManyToManyField(db_table='maison_commodites', related_name='maisons', to='estimation.commodite'),
        ),
    ]
